services:
  symfony:
    build:
      context: ./backend
    container_name: symfony-app
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
    environment:
      - APP_ENV=dev
    networks:
      - app-network

  angular:
    build:
      context: ./frontend
    container_name: angular-app
    ports:
      - "4200:80"
    depends_on:
      - symfony
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
